### ISSUE TITLE
PHP 5.6 compatibility

### ISSUE THREAD

**Issue by DWMcload** [davebarnwell/model-orm-php#11]
forget about this :)

**Comment by davebarnwell** [comment]
Cool only 7.1 dependancies in the lock file are for dev, not production. So yeah should work with 5.6 fine, that said I now only test for 7.1+ as anything <=7.0 is end of life see https://www.php.net/supported-versions.php

**Comment by DWMcload** [comment]
Thanks for replying when even there is no question anymore. 
I updated the version to the latest and received an error which comes from a package which requires php7. But it turned out was one of the other libraries I use. 

Have a nice day!
