### ISSUE TITLE
Cannot install via composer

### ISSUE THREAD

**Issue by DWMcload** [davebarnwell/model-orm-php#8]
I tried to add this repository to my project via composer, but got this error:
 [InvalidArgumentException]                                                                                                                                                                                                    
  Could not find a matching version of package davebarnwell/model-orm-php. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

Also, this repository is not found on packagist. Can you update please to be able to install? (see https://packagist.org/? -> Publishing Packages)
Also it would be nice to speak about installation in the readme file.

**Comment by davebarnwell** [comment]
@DWMcload Great to hear you like the library. I've never placed it on packageist as I've always treated this lib as a side project, although I've used it in my own production projects.

To install via composer you need to define the VCS repo see https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

Something like this will work
```
{
    "minimum-stability": "dev",
    "prefer-stable": true,
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/davebarnwell/model-orm-php"
        }
    ],
    "require": {
        "Freshsauce/Model": "dev-master"
    }
}
```
